name: Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    # Usiamo ubuntu-22.04 che è super stabile per Android ed evita i warning di aggiornamento
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install --no-audit --no-fund

      - name: Add Android platform
        run: npx cap add android

      - name: Capacitor sync
        run: npx cap sync android

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Accept Android Licenses
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Build debug APK
        run: |
          cd android
          ./gradlew assembleDebug --no-daemon

      - name: Rename APK
        run: |
          mv android/app/build/outputs/apk/debug/app-debug.apk registro-neonato-debug.apk

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: registro-neonato-debug-apk
          path: registro-neonato-debug.apk

      - name: Release APK
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Ultima APK debug
          make_latest: true
          files: registro-neonato-debug.apk
